### ISSUE TITLE
侧边栏无序列表渲染问题

### ISSUE THREAD

**Issue by BNTang** [wangyang0210/Cnblogs-Theme-BNDong#10]
![image](https://user-images.githubusercontent.com/78400939/180596172-7799d5cb-09f3-4459-8f6c-c4b7b92beb64.png)

**Comment by wangyang0210** [comment]
这个其实是博客园本身返回的数据存在问题~ 晚上我来调整下~
![image](https://user-images.githubusercontent.com/36377605/180597521-a8abf837-d4a1-4c6f-b6d1-b6146d9631c5.png)

**Comment by wangyang0210** [comment]
https://group.cnblogs.com/topic/117939.html#275004
博客园已经修复了~ 不过为了防止再出现这种情况,我会对数据进行过滤一下~

**Comment by BNTang** [comment]
欧克
