### ISSUE TITLE
homeBanner 动效 失效

### ISSUE THREAD

**Issue by amluckydave** [wangyang0210/Cnblogs-Theme-BNDong#109]
您好，homeBanner - 主页 banner 动效 设置失效；

功能建议：bannerImages - banner 背景图自动切换动效，可以区分homeBanner和articleBanner吗？因为有可能主页有多张图片，而文章页只设置一张图片。

以上，谢谢

**Comment by wangyang0210** [comment]
我丢，这都被你找到了，有点厉害，不过这个是为了国内访问方便，做的一版优化的版本，还没彻底弄完，而且配置和主仓库有些不一样，打算测试通过后，逐步像主仓库提交的，动画效果我记得是分开的，这个我后续关注下看看。

**Comment by amluckydave** [comment]
谢谢 辛苦啦 今天刚迁移到咱们的这个主题，这个homeBanner 还是蛮炫酷的，所以很需要，谢谢啦

**Comment by wangyang0210** [comment]
动效其实和主仓库是一致的，我刚才看了下，当前仓库的版本动画效果是正常的, [测试地址](https://www.cnblogs.com/wangyang1225)，如果你使用当前release版本，那的确可能存在问题。

这个仓库的版本因为支持了npm，并且加入了cdnjs，对比主仓库会有更多国内的镜像源，代码进行了一定的优化，功能上和[Cnblogs-Theme-SimpleMemory](https://github.com/BNDong/Cnblogs-Theme-SimpleMemory)基本没有区别，一般这个仓库我验证完毕就会merge到主仓库里面的，稳定的话还是建议使用主仓库哈。

本周末我会迭代一个版本并完善下文档。

**Comment by amluckydave** [comment]
```
animate: {
        infoName: { enable: true, },
	bannerImages: { enable: true },
	homeBanner: {
		enable: true,
		options: { radius: 15, },
	},
	avatar: { enable: false },
	articleTitle: { enable: false },
	articleBanner: { enable: true },
	background: { 
		particles: { enable: true },
	},
	mouse: {
              click: {
                  enable: false,
                  options: {},
              },
        },
}
```
		
您看我的配置，homeBanner和mouse的click还是都失效，用的是tags下的2.2.17版本

<script src="https://cdn.jsdelivr.net/gh/wangyang0210/cnblogs-theme@v2.2.17/dist/simple-memory.js" defer></script>

css拷贝的是2.2.17下dist中的css

**Comment by wangyang0210** [comment]
正如前面说的那样，你使用的是当前的release（2.2.17）版本，这个版本是有问题的，所以你需要引用当前仓库的版本，再进行一些调整，大致如下：

1. 引入当前仓库版本
<script src="https://cdn.jsdelivr.net/gh/wangyang0210/cnblogs-theme@8393d39/dist/simple-memory.js" defer></script>

2. 使用当前仓库对应的[css](https://github.com/wangyang0210/cnblogs-theme/blob/v2/dist/simple-memory.css)

3. 参考最新的配置文件[config.json5](https://github.com/wangyang0210/cnblogs-theme/blob/v2/src/components/config/config.json5)去调整

**Comment by amluckydave** [comment]
按照您的设置，可能发现bug，只要title为空，动画显示正常，但凡一自定义，动画失效

```
    banner: {
        home: {
            title: [ '1', ],
    },},
```
