### ISSUE TITLE
语言识别不准确

### ISSUE THREAD

**Issue by BNTang** [wangyang0210/Cnblogs-Theme-BNDong#24]
![image](https://user-images.githubusercontent.com/78400939/181457847-b0aa8395-a13e-454d-86fb-1c67638ccd1e.png)

**Comment by wangyang0210** [comment]
> ![image](https://user-images.githubusercontent.com/78400939/181457847-b0aa8395-a13e-454d-86fb-1c67638ccd1e.png)

highlightjs的问题,建议写入代码块时,指定语言类型,我会把博皮中的highlightjs进行升级;
