### ISSUE TITLE
代码块这个语言为啥会这样 出现 language-xxx

### ISSUE THREAD

**Issue by BNTang** [wangyang0210/Cnblogs-Theme-BNDong#37]
![image](https://user-images.githubusercontent.com/78400939/181934182-65318b05-df3d-4425-a003-c0fbcbce9c1b.png)

**Comment by wangyang0210** [comment]
感觉是language-没被替换掉;
- 完整的代码块贴下
- 使用的高亮主题也给下

**Comment by BNTang** [comment]
> 感觉是language-没被替换掉;
> 
> * 完整的代码块贴下
> * 使用的高亮主题也给下

```bash
db.person.aggregate([
    {$limit: 1}
]);
```

主题：an-old-hope

**Comment by BNTang** [comment]
> > 感觉是language-没被替换掉;
> > 
> > * 完整的代码块贴下
> > * 使用的高亮主题也给下
> 
> ```shell
> db.person.aggregate([
>     {$limit: 1}
> ]);
> ```
> 
> 主题：an-old-hope
