### ISSUE TITLE
关于代码块语言渲染问题

### ISSUE THREAD

**Issue by BNTang** [wangyang0210/Cnblogs-Theme-BNDong#51]
- 代码块语言设置为 mongodb-json-query
- 出现如下图所示的错误信息

![image](https://user-images.githubusercontent.com/78400939/184523445-60c22bc3-5bc9-44cc-8217-84963b968da5.png)

**Comment by wangyang0210** [comment]
1. 语言指定存在问题;
2. hljs目前好像是不支持mongodb;
3. 建议不要指定语言,让hljs自己去识别渲染,不过短代码片段,识别精度不高...
