### ISSUE TITLE
关于目录

### ISSUE THREAD

**Issue by BNTang** [wangyang0210/Cnblogs-Theme-BNDong#53]
![image](https://user-images.githubusercontent.com/78400939/184578001-b18df9ab-d6e9-4476-b774-bdb51739a93a.png)

**Comment by wangyang0210** [comment]
这个没有配置,配置的是横向滚动,这个我觉得可以不调整的,目录本来就是方便阅读,如果太少了反而不方便,目前的我觉得挺好的,先开放着~看后续大家反馈~ 多的话,就增加个高度配置项~

**Comment by YaenLi** [comment]
这地方没必要改吧
