### ISSUE TITLE
关于图片展示组件

### ISSUE THREAD

**Issue by BNTang** [wangyang0210/Cnblogs-Theme-BNDong#54]
![image](https://user-images.githubusercontent.com/78400939/184578192-abf64da0-9c3f-437b-bc0e-6f93d5108e07.png)
底部作者声明的图片也被加入到了图片展示列表当中，请问这个应该不加入进去吧

**Comment by wangyang0210** [comment]
哈哈哈,我可以说是个小彩蛋嘛~
