### ISSUE TITLE
文章页面超链接显示样式的问题

### ISSUE THREAD

**Issue by BNTang** [wangyang0210/Cnblogs-Theme-BNDong#62]
![image](https://user-images.githubusercontent.com/78400939/186366715-42289504-12d7-4f8b-a4ab-59584eba4747.png)

**Comment by wangyang0210** [comment]
因为整个的页面宽带是固定的,这个可以优化,但是你这个用正确的markdown语法插入链接会更好;
```html
[Ts声明官方文档](https://xxx.xx)
```

或者你在文章前面或尾部插入脚注,更好;

**Comment by BNTang** [comment]
> 

嗯，我是直接 CV了，这个优化吧
