### ISSUE TITLE
文章分类，分页样式问题

### ISSUE THREAD

**Issue by BNTang** [wangyang0210/Cnblogs-Theme-BNDong#63]
![image](https://user-images.githubusercontent.com/78400939/186367178-ceb2fbe6-e8a8-4520-bf98-3cbb3a61770a.png)

**Comment by wangyang0210** [comment]
分类下的这个可能是博客园本身的bug,等博客园回复下;
![QQ图片20220827175421](https://user-images.githubusercontent.com/36377605/187025337-a530b2bd-8599-4e25-89fc-cd3510a64568.png)

**Comment by wangyang0210** [comment]
博客园官方已经修复

**Comment by BNTang** [comment]
![image](https://user-images.githubusercontent.com/78400939/187041912-78d28229-198f-48a1-8789-55a11a9068c2.png)
，博客园官方的问题修复了，样式还是需要改改
