### ISSUE TITLE
关于文章一行可以显示完毕这里换行了是不是需要优化一下样式

### ISSUE THREAD

**Issue by BNTang** [wangyang0210/Cnblogs-Theme-BNDong#74]
![image](https://user-images.githubusercontent.com/78400939/189638502-c9250cb7-2415-4bcb-8832-f400efba4478.png)

**Comment by wangyang0210** [comment]
这里更多的是本身编写文章的时候需要注意下,就像编码规范一行最多不超过80-100字符一样;
