### ISSUE TITLE
文章页面渲染报错

### ISSUE THREAD

**Issue by BNTang** [wangyang0210/Cnblogs-Theme-BNDong#75]
- 地址：https://www.cnblogs.com/BNTang/articles/15368157.html

![image](https://user-images.githubusercontent.com/78400939/190548108-95a8bbd9-60d7-44e3-b0a4-c959e8275158.png)

**Comment by wangyang0210** [comment]
![GW2D2I8QIM(0A6R_ L 5GTN](https://user-images.githubusercontent.com/36377605/191676999-f769a5a2-9880-44b0-ae70-12be6ed6416f.png)
