### ISSUE TITLE
侧边栏数据统计的样式问题

### ISSUE THREAD

**Issue by BNTang** [wangyang0210/Cnblogs-Theme-BNDong#76]
![image](https://user-images.githubusercontent.com/78400939/194747144-720c1563-eef4-4fb3-9c9f-9378c617ffce.png)
如上如果数据过多文字达到了 关闭侧边栏的叉吧了，这样就不好看，可以参考 BNDong 作者最近更新的样式你看行吗

**Comment by BNTang** [comment]
![image](https://user-images.githubusercontent.com/78400939/194747190-d87ceebf-9702-4364-9296-fbc3883abdb4.png)

**Comment by wangyang0210** [comment]
可以的

**Comment by wangyang0210** [comment]
那大哥又开始更新了嘛(oﾟvﾟ)ノ

**Comment by wangyang0210** [comment]
侧边栏配置增加一个blogStatus来控制吧

**Comment by BNTang** [comment]
> 那大哥又开始更新了嘛(oﾟvﾟ)ノ

哈哈，前几天看到更新了他，他应该有时间抽离出来了
