### ISSUE TITLE
关于侧栏内容

### ISSUE THREAD

**Issue by meloncn** [wangyang0210/Cnblogs-Theme-BNDong#8]
尊敬的开发者您好！您的主题非常棒但是我有一点困惑，使用了您的主题后侧栏里的阅读排行和推荐排行显示不出来是什么情况？望指点一二
![image](https://user-images.githubusercontent.com/54462952/86778350-d897c180-c08c-11ea-894a-2fb221cbb3b0.png)

**Comment by wangyang0210** [comment]
这个是可以配置的哦~
![image](https://user-images.githubusercontent.com/36377605/88001435-babd6880-cb32-11ea-855d-7d064aa0069f.png)

**Comment by wangyang0210** [comment]
![image](https://user-images.githubusercontent.com/36377605/88001490-d7f23700-cb32-11ea-9014-cdc27e79160e.png)
