### ISSUE TITLE
友联页面两个问题

### ISSUE THREAD

**Issue by BNTang** [wangyang0210/Cnblogs-Theme-BNDong#80]
![image](https://user-images.githubusercontent.com/78400939/205061221-dab920d3-608e-4acd-8209-1abe3502d7f3.png)
1.name 内容过多导致样式不好看
2.gif 图片显示的问题

**Comment by wangyang0210** [comment]
gif图片的加载没有问题,你可以看下是不是因为图片无法访问导致的加载失败,显示问题已优化
