### ISSUE TITLE
纪念日的样式问题，12-13 这个日期不在当中样式还是生效了

### ISSUE THREAD

**Issue by BNTang** [wangyang0210/Cnblogs-Theme-BNDong#81]
![image](https://user-images.githubusercontent.com/78400939/207208732-3c7c6930-75de-4d6f-897e-5b148ce8de05.png)
![image](https://user-images.githubusercontent.com/78400939/207208802-ca075ffc-1743-4992-ad28-578c213b205c.png)

**Comment by wangyang0210** [comment]
主题默认国家公祭日为重大纪念日.
