### ISSUE TITLE
文章的 h1-h6 出现特殊字符是不是渲染不了

### ISSUE THREAD

**Issue by BNTang** [wangyang0210/Cnblogs-Theme-BNDong#82]
![image](https://user-images.githubusercontent.com/78400939/209923503-1f80eba5-a99b-4193-91d0-39da93b41249.png)

- 文章地址：https://www.cnblogs.com/BNTang/articles/14243256.html

**Comment by wangyang0210** [comment]
渲染的时候被当作了标签,转换下就好了,已修复;
