### ISSUE TITLE
文章的层级样式滚动BUG，如下图所示我已经定在了（金额大小写转换）可是右侧的样式还没有变化

### ISSUE THREAD

**Issue by BNTang** [wangyang0210/Cnblogs-Theme-BNDong#84]
![image](https://user-images.githubusercontent.com/78400939/211477658-cd875663-baad-499d-92ae-f35a6f2bfa27.png)

**Comment by BNTang** [comment]
文章链接：https://www.cnblogs.com/BNTang/articles/17036468.html

**Comment by wangyang0210** [comment]
我去试了下，滚动是正常的；
