### ISSUE TITLE
titleMsg 内容过长，是不是需要进行样式优化例如超过多少，后面的以 "..." 来显示

### ISSUE THREAD

**Issue by BNTang** [wangyang0210/Cnblogs-Theme-BNDong#89]
![image](https://user-images.githubusercontent.com/78400939/224952561-6c5ca6da-9d8e-40db-9f74-61299c811c7c.png)

**Comment by wangyang0210** [comment]
是个不错的点子，不过这其实是个类似于公告的功能，如果直接省略的话，有点违背本意了；
增加个配置吧，来控制是否隐藏；开启后默认进行省略，鼠标hover过去展示全部内容；

**Comment by BNTang** [comment]
> 是个不错的点子，不过这其实是个类似于公告的功能，如果直接省略的话，有点违背本意了； 增加个配置吧，来控制是否隐藏；开启后默认进行省略，鼠标hover过去展示全部内容；

是的，显示太多内容会撑大

**Comment by BNTang** [comment]
![image](https://user-images.githubusercontent.com/78400939/225521194-bd91dea5-5064-4ff1-b4a2-d74c7afed741.png)

**Comment by BNTang** [comment]
优化方案，我觉得应该可以
