### ISSUE TITLE
字体显示问题

### ISSUE THREAD

**Issue by Alex950808** [wangyang0210/Cnblogs-Theme-BNDong#9]
![image](https://user-images.githubusercontent.com/23734094/180595386-0194a5d4-c132-4433-a350-cbb8161ebcaa.png)
![image](https://user-images.githubusercontent.com/23734094/180595420-07a9696c-a8f6-4d4a-b279-7b242349e3f0.png)
能把字体也搞一下就好了

**Comment by wangyang0210** [comment]
哈哈哈~ 没有太明白,是希望继续用这个字体是嘛~

**Comment by wangyang0210** [comment]
因为google的这个字体,仓库好像少了东西,影响到打包了,所以这边临时就直接干掉了~ 我晚上研究下~

**Comment by wangyang0210** [comment]
已在dev分支修复
