### ISSUE TITLE
文章不居中问题

### ISSUE THREAD

**Issue by Jausmai** [wangyang0210/Cnblogs-Theme-BNDong#97]
![image](https://github.com/wangyang0210/cnblogs-theme/assets/137151216/5606d041-dc96-4045-9359-b127b99d944f)
设置后文章偏右，不居中显示

**Comment by wangyang0210** [comment]
设置里禁用下默认的css
![098d38f506f77fe04d46f168e164297e](https://github.com/wangyang0210/cnblogs-theme/assets/36377605/e2b742eb-a2ef-49b8-b76b-809cf7ffb5c0)
